### ISSUE TITLE
Create Terms of Service functionality

### ISSUE THREAD

**Issue by brianrisk** [brianrisk/qwaver#15]
We want users to always have agreed to the latest terms of service.  If they have not, then they are presented with a page that has the text of the TOS and an "Agree" button.  

## Summary of code changes:

A new model in the `user` app called `TermsOfService`.  It will have two fields:
Character field: `title`
text field: `text`
DateTimeField:  `default=timezone.now`

Update `Profile` model to have a new integer field named something like `latest_tos_agreed_to`.  This value can also be `None` if they are new and have agreed to nothing yet.  This field will contain the id of the `TermsOfService` model to which the user has agreed.

A `terms_of_service.html` template.  There should be nothing else on the page (e.g. no menu), so the template should not inherit from base.html.  However, it will contain a lot of the styling info from base.html so that it looks like the rest of the site.  The template will include the 'title' and 'text' fields of the TermsOfService object in the context.  Also there will be an empty form, no fields, but simply a button that says "I agree" that submits to the `terms_of_service` url path.

A `terms_of_service` view.  
this will have an 'if' that determines if we are displaying a terms of service or if we are recording that the user agreed to a terms of service.  Other code in the code base will have examples.  Search for:   `if request.method == 'POST':`
If POST:
It will update the `Profile` model of the user to contain the version number of the latest TOS
else:  
This will retrieve the `TermsOfService `with the highest ID, ad that to the context and display it within the `terms_of_service.html` template

A `/terms_of_service` url in the `user` app `urls.py`

Implement it so that if the user is logged in and has not agreed to the latest TOS, then they are automatically directed to the `terms_of_service` url

**Comment by Ho1yShif** [comment]
Hey Brian,
I committed the `TermsOfService` model on a new branch called `feature-tos_updates`. I'm currently working on updating the `Profile` model. I see that you already have a Boolean field called `accept_terms_of_service` in there.
I'd like to delete it, since the same info will be conveyed in our new field `latest_tos_agreed` by including a default value of `None`, but I wanted to discuss that design decision with you first.
In the future, would you like me to make those kinds of decisions myself or bring them up in issue comments like this? Thanks!

**Comment by brianrisk** [comment]
@Ho1yShif  yes!  👍 to deleting `accept_terms_of_service`. Regarding how to handle in the future, whatever your judgement is at the time.  I usually spot the changes in the diff regardless.  In this case, it's pretty clear that `accept_terms_of_service` was an old, unused bit of code that the new code would replace, so it's the right call getting rid of it.

**Comment by Ho1yShif** [comment]
Great, thanks! I just pushed a commit to remove `accept_terms_of_service`.
